### ISSUE TITLE
Withdraw noted items bug

### ISSUE THREAD

**Issue by TazE-scripts** [Torwent/WaspLib#114]
If the item is noted `TRSBankItem.setup('Bones', 2, True)`, then it will try to withdraw item 3x the quantity and will always take a screenshot since `SelfBankEmpty = Bank.IsOpen()`

**To Reproduce**
```pascal
{$I SRL-T/osr.simba}
{$I WaspLib/osr.simba}

var
  RSW: TRSWalker;
  ItemToWithdraw: TRSBankItem;
  BankScript: TBaseBankScript;

begin
  ItemToWithdraw := TRSBankItem.setup('Bones', 2, True);
  RSW.Setup([RSRegions.GRAND_EXCHANGE]);
  if Bank.WalkOpen then
    BankScript.Withdraw(ItemToWithdraw);
end.    
```

**Expected behavior**
Should only withdraw the quantity = 2

**Screenshots**
https://discord.com/channels/795071177475227709/864816381051535390/1171609655605219360

**Additional context**
Bug could be related to commit: https://github.com/Torwent/WaspLib/commit/2c0bb359f4251d60dc128999d3c8549f770c84e2

**Comment by TazE-scripts** [comment]
Additionally found another problem of the return true/false depending if noted or not:
if successful withdraw of noted item then return false
if successful withdraw of un-noted item then return true

**Comment by Torwent** [comment]
fixed
